### ISSUE TITLE
这到底是redis数据库还是客户端？

### ISSUE THREAD

**Issue by skyformat99** [danielshaving/xredis#1]
该怎么使用啊。
有windows下的版本吗？
谢谢

**Comment by zgzhanghao** [comment]
没有windows版本，支持客户端和redis 数据库

**Comment by skyformat99** [comment]
就是说，既可以当做数据库服务器，也可以当做连接
redis数据库的类直接用?
牛🐮

**Comment by skyformat99** [comment]
大牛牛，这个应该怎么用啊?
指点一下吧。

**Comment by zgzhanghao** [comment]
直接makfile ./redis-server 0.0.0.0 6379 0 0

**Comment by skyformat99** [comment]
谢谢。这就是一个内存数据库redis?
有自动存硬盘的功能嘛？
可以用在哪些场景?

**Comment by zgzhanghao** [comment]
和redis一样啊，你参考redis文档。

**Comment by skyformat99** [comment]
这个也能够存在磁盘嚒？
